baseURL: https://stemchica.me/
languageCode: en-us
title: STEM Chica
theme: monopriv-master
description: "Showcasing my projects and journey as a First-Generation Latina in STEM. I am passionate of Science & Technology and want to inspire others like me to pursue STEM and own up to being the outlier in their group."
copyright: "&copy;2022 STEMCHICA Powered by Ericka Fernanda Salas-Garcia "

permalinks:
  post: /:year/:month/:day/:slug/

menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/erickasls
    - name: Instagram
      url: https://instagram.com/stemchica