---
title: "I am a Latina Creative & Scientist"
author: "Ericka Salas"
date: 2022-04-20T21:13:14-05:00
categories: ["R"]
tags: ["About", "Me", "Latina", "Scientist"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```
## Who Am I? What is STEM Chica?
##### post by Ericka Salas


### My Journey
I am currently a Senior at The University of Texas at Austin studying Computational Biology with a minor in Elements of Computer Science and Applied Statistical Modeling. My journey with Science, Technology, Engineering, and Mathematics (STEM) all started as a kid when I would create Math games for fun in my elementary after-school computer lab class. I became so passionate with the idea of learning new truths of the world through STEM and then learning how to apply these truths to create a better world. 

When I discovered my passion for science and math in Elementary school, I decided to saturate this thrill with different after school activities that involved Math, History, & Science Though, after moving across the country in Middle School, I did gear a different path for a few years. I acquired an interest in sports and the human body and eventually obsessed with nutrition and learning about human biology. 

So I applied to a Magnet high school that was an hour away from my hometown, Pharr, TX. For 4 years, I would take a bus to South Texas ISD Medical Professions High School, which was 52 miles away from my house. Sometimes, I wanted to give up and go back to the high school that was a mile away from home, but I am so glad I never did. 

At this High School, I was able to train my scientific brain daily. However, I realized I did not want to pursue Health Care (I went changing around from Doctor, Physician Assistant, Nurse to Pharmacist). I was awarded twice, International Awards for HOSA Forensic Medicine, and in this I discovered my love for learning, curiosity, and what I truly wanted to be. My Computer Science and Robotics experience here influenced me that I wanted to be in technology, science, and behind the scenes of the evolution of the world. 

It wasn't always rainbows and butterflies. In High School, I was so focused on trying to leave the Rio Grande Valley. It was my ticket out of the different scarcity mindsets that I grew up with. As a first-generation, Mexican-American, my 6 sense became learning to read the different changes in environments and adapt to the constant changes. 

### STEM & Learning Is My True Passion 

I moved a lot, I grew up low-income in a family of Immigrants and was the only citizen for 21 years in the family. As I was trying to solve all the problems around me, I found the the things that kept me going and it was learning the revolutionizing truths of the present moment in the world around me. Because the Truth is what gave me comfort and set me free from my own prejudices and biases that were subconsciously disintegrating me. 

I sit back into 9 year-old me and feel her happiness as she solves math problems and creates creative solutions in the computer lab at school. I do everything for her, because that version of me deserves to live in pursuit of discovering and creating new truths for a better world. 

So 2nd semester of my Freshmen year at UT Austin, I switch from Public Health (Pre-Pharmacy) to Computational Biology. I tried applying to UT Austin 
Computer Science Program, but I was denied twice. So I picked up Computer Science and Applied Statistics as 2 different minors. 

I am glad I got rejected from UTCS. This redirection allowed me to discover my interest and desire for Data Science. I joined a Research Group that was composed of Undergraduate and Graduate Students for Dr. Mbemba Jabbi at The Department of Psychiatry at Dell Medical School. I became exposed to Bioinformatics and my experience was tied to Machine Learning and Data Science concepts. 

### My Research Experience 
My research involved extracting genes from modules of interest (Calculated from a PCA - Principal Component Analysis) and finding ways to understand pathways that are affected by patients with Mood Disorders. 

Across multiple Mood Disorder samples, I ran a WGCNA R software package about 1,000 plus times. This weighted correlation network analysis (WGCNA) is a collection of R functions that allows to detect the correlation patterns across modules using eigengene network methodology across metadata samples.

For my research I gained an award with my two group mates for The Best Research Poster in the Computational Sciences category in the 2020 Undergraduate Research Forum UT Austin. Throughout my research journey with Dr. Jabbi and my research Supervisor Dhivya, I learned that I enjoy learning new technology tools that can impact any aspect of the world if you set your mind to it. So I deviated from the research world after I gained an internship with USAA. This was different than being in a computational research and work environment. I loved the balance that I discovered and found interest in old hobbies such as reading, journaling, writing, and movie/photo editing. The industry internship experience as a Data Engineer taught me that my passion is in the world of Technology & Data. It is the building block of creating life that is able to value the present moment. It is exponentially impacting the world. And I simply want to be a part of that. 

### Why STEM CHICA???
STEM Chica is meant for me to showcase theories, ideas, thoughts about science, tech, math, and engineering (STEM). I also am going to be a bit vulnerable in the challenging patches of my journey. The reason I call it "chica" is because it represents my Latinidad since I grew up as a first-generation Mexican American. My goal is to help and inspire other women in STEM and younger generations to push through the struggles of reality and become the growing generation that revolutionizes technology to the highest good of all and harm to none. 

### Check Out My Portfolio of Work :) 
Throughout my research and college experience as an undergraduate student at UT Austin, this is a link to the portfolio of work I like to showcase. 

